# Generated by Django 5.0.6 on 2024-06-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
                ('phoneNumber', models.IntegerField(null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Pswd', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
