# Generated by Django 5.0.6 on 2024-06-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_deckline', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=9, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
    ]
