# Generated by Django 5.0.6 on 2024-06-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_deckline', '0004_financialyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basicinformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
                ('Address', models.CharField(max_length=20, null=True)),
                ('Website', models.CharField(max_length=50, null=True)),
                ('phone1', models.CharField(max_length=50, null=True)),
                ('phone2', models.CharField(max_length=50, null=True)),
                ('e_mail1', models.EmailField(max_length=50, null=True)),
                ('e_mail2', models.EmailField(max_length=50, null=True)),
                ('Gstino', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
