# Generated by Django 5.0.6 on 2024-06-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_deckline', '0005_basicinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='windowblinds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, null=True)),
                ('productcode', models.CharField(max_length=15, null=True)),
                ('productname', models.CharField(max_length=20, null=True)),
                ('taxpercent', models.CharField(max_length=50, null=True)),
                ('hsncode', models.CharField(max_length=50, null=True)),
                ('unit', models.CharField(max_length=50, null=True)),
                ('unitprice', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
