# Generated by Django 5.0.6 on 2024-06-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_deckline', '0006_windowblinds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=15, null=True)),
                ('Productcode', models.CharField(max_length=20, null=True)),
                ('Productname', models.ImageField(max_length=50, null=True, upload_to='')),
                ('Tax', models.CharField(max_length=50, null=True)),
                ('Hsncode', models.CharField(max_length=50, null=True)),
                ('Unit', models.CharField(max_length=50, null=True)),
                ('Unitprice', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
