# Generated by Django 5.0.6 on 2024-06-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_deckline', '0007_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='employeeform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joiningdate', models.DateField(null=True)),
                ('employeeid', models.CharField(max_length=20, null=True)),
                ('firstname', models.CharField(max_length=50, null=True)),
                ('lastname', models.DateField(null=True)),
                ('dateofbirth', models.CharField(max_length=50, null=True)),
                ('e_mail1', models.EmailField(max_length=50, null=True)),
                ('phone1', models.CharField(max_length=20, null=True)),
                ('phone2', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=60, null=True)),
                ('designation', models.CharField(max_length=20, null=True)),
                ('idcardtype', models.CharField(max_length=20, null=True)),
                ('idcardnumber', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='basicinformation',
            name='Logo',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
