# Generated by Django 5.0.6 on 2024-06-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_deckline', '0008_employeeform_basicinformation_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeform',
            name='photo',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='employeeform',
            name='lastname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
