# Generated by Django 5.0.6 on 2024-06-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_deckline', '0009_employeeform_photo_alter_employeeform_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeform',
            name='doc1',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='employeeform',
            name='doc2',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
