# Generated by Django 5.0.6 on 2024-06-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_deckline', '0010_employeeform_doc1_employeeform_doc2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_id', models.CharField(blank=True, max_length=20, null=True)),
                ('inquiry_date', models.DateField(blank=True, null=True)),
                ('cust_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('alternate_no', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(choices=[('lead_approved', 'Lead Approved'), ('order_taken', 'Order Taken')], default='lead_approved', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
