# Generated by Django 5.0.6 on 2024-06-20 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_deckline', '0011_lead_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home_deckline.staff'),
        ),
    ]
