# Generated by Django 5.0.6 on 2024-06-27 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_deckline', '0012_lead_assigned_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='windowblindtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, null=True)),
                ('width', models.CharField(max_length=20, null=True)),
                ('height', models.CharField(max_length=20, null=True)),
                ('sqft', models.CharField(max_length=20, null=True)),
                ('ratepermeter', models.CharField(max_length=20, null=True)),
                ('unit', models.CharField(max_length=20, null=True)),
                ('qty', models.CharField(max_length=20, null=True)),
                ('totalsqft', models.CharField(max_length=20, null=True)),
                ('price', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='windowblindtable1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quatationnumber', models.CharField(max_length=20, null=True)),
                ('dateofreceipt', models.DateField(max_length=20, null=True)),
                ('totalamount', models.CharField(max_length=20, null=True)),
                ('pastingcharge', models.CharField(max_length=20, null=True)),
                ('totalqty', models.CharField(max_length=20, null=True)),
                ('gsttotal', models.CharField(max_length=20, null=True)),
                ('discount', models.CharField(max_length=20, null=True)),
                ('others', models.CharField(max_length=20, null=True)),
                ('netamount', models.CharField(max_length=20, null=True)),
                ('name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home_deckline.lead')),
                ('productname', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home_deckline.windowblinds')),
            ],
        ),
    ]
