# Generated by Django 5.0.6 on 2024-06-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_deckline', '0013_windowblindtable_windowblindtable1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowblindtable1',
            name='dateofreceipt',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
