# Generated by Django 5.0.6 on 2024-06-27 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_deckline', '0014_alter_windowblindtable1_dateofreceipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windowblindtable1',
            name='name',
        ),
        migrations.RemoveField(
            model_name='windowblindtable1',
            name='productname',
        ),
        migrations.AddField(
            model_name='windowblindtable',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home_deckline.lead'),
        ),
        migrations.AddField(
            model_name='windowblindtable',
            name='productname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home_deckline.windowblinds'),
        ),
    ]
