# Generated by Django 5.0.6 on 2024-07-03 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_deckline', '0015_remove_windowblindtable1_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windowblindtable',
            name='height',
        ),
        migrations.RemoveField(
            model_name='windowblindtable',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='windowblindtable',
            name='width',
        ),
        migrations.AlterField(
            model_name='windowblindtable',
            name='productname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home_deckline.windowblinds'),
        ),
    ]
