# Generated by Django 5.0.6 on 2024-07-03 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_deckline', '0016_remove_windowblindtable_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windowblindtable1',
            name='totalqty',
        ),
    ]
